
CONFIG_ZMK_KEYBOARD_NAME="RISATENO"

# ==================== Bluetooth ====================
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_DEVICE_NAME="RISATENO"

CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DIS=y
CONFIG_BT_DIS_MANUF="ZMK"
CONFIG_BT_DIS_PNP=y

# Улучшение стабильности соединения
CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=5000
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=n


CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=128
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=10
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=10
CONFIG_ZMK_COMBO_HOLD_TAP_COMPAT=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY=n


CONFIG_LED_STRIP=n
#CONFIG_ZMK_RGB_UNDERGLOW=n
#CONFIG_WS2812_STRIP=n

# ZMK Studio
#CONFIG_ZMK_STUDIO=y